name: Distributed E-Voting Cassandra Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  evoting-simulation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cassandra-driver || echo "Cassandra driver installation attempted"
    
    - name: Run distributed e-voting simulation
      run: |
        python main.py
    
    - name: Upload output artifact
      uses: actions/upload-artifact@v3
      with:
        name: output-csv
        path: output.csv
        retention-days: 30
